# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('quantity', models.IntegerField(default=1)),
                ('notes', models.TextField()),
                ('stage', models.CharField(choices=[('P', 'Proposed'), ('W', 'Wanted'), ('O', 'Ordered'), ('R', 'Recieved'), ('A', 'Archived')], default='P', max_length=1)),
            ],
        ),
    ]
