# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInventory', '0002_auto_20161109_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Card',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='active',
            new_name='archived',
        ),
        migrations.AlterField(
            model_name='board',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
