# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInventory', '0003_auto_20161114_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='active',
        ),
        migrations.AddField(
            model_name='board',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
