# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInventory', '0004_auto_20161223_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='add',
            field=models.TextField(default=b'All'),
        ),
        migrations.AddField(
            model_name='board',
            name='delete',
            field=models.TextField(default=b'All'),
        ),
        migrations.AddField(
            model_name='board',
            name='manage',
            field=models.TextField(default=b'All'),
        ),
        migrations.AddField(
            model_name='board',
            name='move',
            field=models.TextField(default=b'All'),
        ),
        migrations.AddField(
            model_name='board',
            name='read',
            field=models.TextField(default=b'All'),
        ),
    ]
