# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('SimpleInventory', '0005_auto_20170120_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='add',
        ),
        migrations.RemoveField(
            model_name='board',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='board',
            name='manage',
        ),
        migrations.RemoveField(
            model_name='board',
            name='move',
        ),
        migrations.RemoveField(
            model_name='board',
            name='read',
        ),
        migrations.AddField(
            model_name='board',
            name='addGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='board',
            name='deleteGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='board',
            name='manageGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='board',
            name='moveGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='board',
            name='readGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.Group'),
        ),
    ]
