# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-21 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInventory', '0006_auto_20170120_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': (('create_board', 'Can create a order board'),)},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'permissions': (('modify_stages', 'Can modify board stages'),)},
        ),
    ]
