# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stage',
            field=models.CharField(choices=[('W', 'Wanted'), ('O', 'Ordered'), ('R', 'Recieved')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
