# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderboard', '0004_auto_20160924_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
